# Generated by Django 4.0.4 on 2022-12-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Order'), (2, 'follow'), (3, 'Post Notification'), (4, 'Became a Vendor')]),
        ),
    ]
