# Generated by Django 4.0.4 on 2022-05-06 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date',
            new_name='date_posted',
        ),
    ]
