# Generated by Django 4.0.4 on 2022-10-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='download_EPBN0x6.jpg', upload_to='profile_picture'),
        ),
    ]
