# Generated by Django 4.0.4 on 2022-10-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile_picture/download_EPBN0x6.jpg', upload_to='profile_picture'),
        ),
    ]
