# Generated by Django 4.0.4 on 2022-11-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Order'), (2, 'follow'), (3, 'Post Notification')]),
        ),
    ]
