# Generated by Django 4.0.4 on 2022-11-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_order'),
        ('users', '0009_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='market.order'),
        ),
    ]
