# Generated by Django 4.0.4 on 2022-11-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_order'),
        ('users', '0010_notification_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='orders',
            field=models.ManyToManyField(blank=True, to='market.checkout'),
        ),
    ]
