# Generated by Django 4.0.4 on 2022-11-06 15:02

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Select Category', max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('complete', models.BooleanField(blank=True, default=False, null=True)),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=30)),
                ('ordered', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(default='2placeholder_test_b9l9NT5.png', upload_to='product_images')),
                ('description', models.TextField(default='')),
                ('product_purchase', models.IntegerField(default=0)),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('delivery_period', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='2placeholder_test_b9l9NT5.png', upload_to='product_images')),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('about', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.IntegerField(choices=[(1, 'B.Sc.'), (2, 'M.Sc.'), (3, 'M.A.'), (4, 'M.Sc.'), (5, 'LLB'), (6, 'Others')], default=6)),
                ('account_visit', models.IntegerField(default=0)),
                ('account_engaged', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('twitter_url', models.URLField(default='')),
                ('instagram_url', models.URLField(default='')),
                ('skills', models.CharField(default='', max_length=20)),
                ('paid_until', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
