# Generated by Django 4.0.4 on 2022-05-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='education',
            field=models.IntegerField(choices=[(1, 'B.Sc.'), (2, 'M.Sc.'), (3, 'M.A.'), (4, 'M.Sc.'), (5, 'LLB'), (6, 'Others')], default=6),
        ),
    ]
