# Generated by Django 4.0.4 on 2022-11-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='paystack_public_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='paystack_secret_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
