# Generated by Django 4.0.4 on 2022-05-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_vendor_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='instagram_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='vendor',
            name='twitter_url',
            field=models.URLField(default=''),
        ),
    ]
