# Generated by Django 4.0.4 on 2022-05-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_vendor_instagram_url_vendor_twitter_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='skills',
            field=models.CharField(default='', max_length=20),
        ),
    ]
