# Generated by Django 4.0.4 on 2022-05-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_vendor_paid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
