# Generated by Django 4.0.4 on 2022-05-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_vendor_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
