# Generated by Django 4.0.4 on 2022-11-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_product_rating_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='current_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='total_earnings',
            field=models.FloatField(default=0),
        ),
    ]
