# Generated by Django 4.0.4 on 2022-11-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_vendor_current_balance_vendor_total_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='withdrawal_password',
            field=models.CharField(default='', max_length=4),
        ),
    ]
