# Generated by Django 4.0.4 on 2022-05-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_period',
            field=models.IntegerField(default=0),
        ),
    ]
