# Generated by Django 4.0.4 on 2022-12-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_remove_vendor_paystack_public_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='vendorreview',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='order',
            name='default_order_item',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='default_price',
            field=models.FloatField(default=0),
        ),
    ]
