# Generated by Django 4.0.4 on 2022-05-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_productreview_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
