# Generated by Django 4.0.4 on 2022-12-02 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_checkout_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='default_product',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.product'),
        ),
    ]
