# Generated by Django 4.0.4 on 2022-05-25 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_checkout_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
