# Generated by Django 4.0.4 on 2022-12-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_productreview_default_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_fee',
            field=models.FloatField(default=10),
        ),
    ]
