# Generated by Django 4.0.4 on 2023-06-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_product_shipping_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='withdrawal_password',
            new_name='withdrawal_pin',
        ),
        migrations.AddField(
            model_name='vendor',
            name='image',
            field=models.ImageField(default='profile_picture/download_EPBN0x6.jpg', upload_to='profile_picture'),
        ),
    ]
