# Generated by Django 4.0.4 on 2023-06-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='longitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
