# Generated by Django 4.0.4 on 2023-06-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_visitor_city_visitor_country_visitor_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='latitude',
            new_name='timezone',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='longitude',
        ),
    ]
